# La base de NumPy - ndarray

Toda la libería de NumPy se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array).<br/>

### Características básicas de ndarray

<ul>
<li>Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b></li>
<li>Todos los elementos de un ndarray deben tener <b>EL MISMO TIPO</b>.</li>
<li>El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.</li>
<li>Pero la organización de esos elementos entre diferentes dimensiones sí puede modificarse</li>
</ul>

### Uso básico de cualquier elemento de NumPy

Hay que recordar que NumPy no es un módulo del core de Python por lo que SIEMPRE habrá que importarlo de forma completa o componente a componente.

In [1]:
import numpy as np

### Creación básica de ndarrays

Existen varias formas de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creación de un ndarray cuyos elementos son una secuencia numérica

In [2]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
array_secuencia_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2

array([5, 6, 7, 8, 9])

In [4]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#### Creación de un ndarray a partir de una secuencia básica de Python

In [5]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
type(array_basico)

numpy.ndarray

In [6]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Consulta de la composición de un ndarray

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [7]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
# Tipo de dato (único)
array.dtype

dtype('int32')

In [9]:
# Número de dimensiones
array.ndim

2

In [10]:
# Forma/Dimensiones
array.shape

(3, 4)

In [11]:
# Número total de elementos
array.size

12

### Operaciones aritméticas entre ndarrays y escalares

In [12]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [13]:
# Suma
array + 5

array([ 6.,  7.,  8.,  9., 10., 11.])

In [14]:
# Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [15]:
# Multiplicación
array * 3

array([ 3.,  6.,  9., 12., 15., 18.])

In [16]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [17]:
# División entera
array // 2

array([0., 1., 1., 2., 2., 3.])

In [18]:
# Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [19]:
# Asignación con operador
array += 1
array

array([2., 3., 4., 5., 6., 7.])

### Operaciones aritméticas entre ndarrays

<b>IMPORTANTE:</b> Los dos términos de la operación tienen que ser ndarrays de las mismas dimensiones y forma. Se aplica la operación elemento a elemento.

In [20]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [21]:
# Suma (elemento a elmento)
array + array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [22]:
# Resta (elemento a elmento)
array - array

array([0., 0., 0., 0., 0., 0.])

In [23]:
# Multiplicación (elemento a elmento)
array * array

array([ 1.,  4.,  9., 16., 25., 36.])

In [24]:
# División (elemento a elmento)
array / array

array([1., 1., 1., 1., 1., 1.])

In [25]:
# Asignación con operador
array += array
array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [26]:
# Suma de ndarrays de distinto tamaño
#array1 = np.array([1, 2, 3 ,4, 5])
#array + array1
#creo que error

### Indexación y slicing básico

En ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python. Es decir, se utiliza la indexación [a:b:c].

In [27]:
array = np.arange(1, 11)

In [28]:
# Indexación con primer parámetro
array[2]

3

In [29]:
# Indexación con primer y segundo parámetro
array[2:5]

array([3, 4, 5])

In [30]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [31]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

En ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:<br/>
<ul>
<li><b>Mediante indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li><b>Mediante indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [32]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [33]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [34]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
# Indexación recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [36]:
# Indexación recursiva tercer nivel
array[1][0][3]

12

In [37]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [38]:
# Indexación con comas tercer nivel
array[1, 0, 3]

12

In [39]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [40]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

Del mismo modo a como ocurre en Python básico, se puede utilizar la indexación/slicing para modificar secciones del contenido de un ndarray.

In [41]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [42]:
# Modificación de una posición
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [43]:
# Modificación de un slice
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

### Indexación y slicing booleano

In [44]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [45]:
datos = np.random.randn(4, 4)
datos

array([[-1.00274324, -0.4084265 ,  1.3380111 , -1.45606847],
       [ 1.98910986, -0.37588616, -0.84508035, -0.77632413],
       [-0.4097059 ,  0.97993709,  0.38420063,  0.31243522],
       [ 1.5313249 ,  0.34935893,  1.48212719, -1.0302435 ]])

In [46]:
# Indexación/slicing booleano sobre valores
datos[datos < 0]

array([-1.00274324, -0.4084265 , -1.45606847, -0.37588616, -0.84508035,
       -0.77632413, -0.4097059 , -1.0302435 ])

In [47]:
# Máscara booleana
personas == 'Miguel'

array([ True, False, False,  True])

In [48]:
# Indexación/slicing mediante máscara
datos[personas == 'Miguel']

array([[-1.00274324, -0.4084265 ,  1.3380111 , -1.45606847],
       [ 1.5313249 ,  0.34935893,  1.48212719, -1.0302435 ]])

In [49]:
# Indexación/slicing mediante máscara y básico combinado
datos[personas == 'Miguel', ::2]

array([[-1.00274324,  1.3380111 ],
       [ 1.5313249 ,  1.48212719]])

In [50]:
# Indexación/slicing mediante máscara negativo por operador
datos[personas != 'Miguel']

array([[ 1.98910986, -0.37588616, -0.84508035, -0.77632413],
       [-0.4097059 ,  0.97993709,  0.38420063,  0.31243522]])

In [51]:
# Indexación/slicing mediante máscara negativa por signo
datos[~(personas == 'Miguel')]

array([[ 1.98910986, -0.37588616, -0.84508035, -0.77632413],
       [-0.4097059 ,  0.97993709,  0.38420063,  0.31243522]])

De nuevo, podemos utilizar indexación/slicing booleano para realizar modificaciones sobre el contenido de un ndarray.

In [52]:
array = np.random.randn(7, 4)
array

array([[-0.58532354, -0.38580878, -0.3351776 ,  0.64470764],
       [-1.32117637, -0.90669998,  0.27861591, -0.21342596],
       [-0.49602869, -0.11216961,  0.63945784,  0.12814784],
       [ 0.3838083 ,  0.74519235, -0.03435614,  1.13077963],
       [ 0.30351693, -0.3219058 , -0.64855295,  0.5779703 ],
       [ 1.11696977, -0.60721502,  2.08674202, -1.81859631],
       [-0.92545409,  0.05404194, -1.71134704,  1.78966387]])

In [53]:
# Eliminación de valores negativos mediante slicing
array[array < 0] = 0
array

array([[0.        , 0.        , 0.        , 0.64470764],
       [0.        , 0.        , 0.27861591, 0.        ],
       [0.        , 0.        , 0.63945784, 0.12814784],
       [0.3838083 , 0.74519235, 0.        , 1.13077963],
       [0.30351693, 0.        , 0.        , 0.5779703 ],
       [1.11696977, 0.        , 2.08674202, 0.        ],
       [0.        , 0.05404194, 0.        , 1.78966387]])

### Indexación y slicing basado en secuencias de enteros - Fancy indexing

In [54]:
array = np.empty((8, 4))
for i in range(8):
    array[i] = i
array    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [55]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [56]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

También podemos indexar de manera arbitraria en múltiples dimensiones, utilizando para ello, una secuencia de enteros por cada dimensión. El resultado será la combinación de secuencias.

In [57]:
array = np.arange(32).reshape((8, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [58]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [59]:
# Indexación/slicing con una secuencia de varios niveles (región resultante)
array[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Trasposición y modificación de ejes/dimensiones

In [60]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
# Modificación de ejes/dimensiones
array2 = array.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
# Trasposición de ejes/dimensiones"
array2.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

**Axis**

Valor 0: Aplicará la función por filas


Valor 1: Aplicará la función por columnas

In [63]:
array2.sum(axis=1)

array([10, 35, 60])

In [64]:
array2.sum(axis = 0)

array([15, 18, 21, 24, 27])

# Operaciones sobre ndarrays

In [65]:
import numpy as np

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [66]:
array = np.array([1,2,3,4,5])
np.abs(array)

array([1, 2, 3, 4, 5])

In [67]:
np.sign(array)

array([1, 1, 1, 1, 1])

In [68]:
np.ceil(array)

array([1., 2., 3., 4., 5.])

#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [69]:
array1 = np.random.randn(5, 5)
array1

array([[ 1.17141364, -0.26355622,  0.23373103,  0.84342601,  0.11431285],
       [ 0.07593065,  0.70401103, -1.02362587,  0.66476856,  1.45500372],
       [ 0.43847616,  0.55775134, -0.77768997, -1.00248836,  0.02876855],
       [ 1.25354118, -1.18127848,  0.26361492,  0.51724183,  0.41037896],
       [ 0.93206076,  1.00820446, -1.03252476, -0.02076836, -0.32630507]])

In [70]:
array2 = np.random.randn(5, 5)
array2

array([[-0.56030167, -2.26846169, -0.27679952, -0.39994822,  0.56653627],
       [-0.01275591, -0.48563267,  1.43575905, -0.66913643,  0.92372724],
       [-0.79033493,  2.78758001, -1.99959917, -0.34740973,  0.3379734 ],
       [ 0.84844114, -0.69517525,  0.21164257, -0.3976746 ,  0.53314874],
       [-1.03981332,  0.2348126 ,  0.07876817,  1.95292515, -0.09074323]])

In [71]:
np.minimum(array1, array2)

array([[-0.56030167, -2.26846169, -0.27679952, -0.39994822,  0.11431285],
       [-0.01275591, -0.48563267, -1.02362587, -0.66913643,  0.92372724],
       [-0.79033493,  0.55775134, -1.99959917, -1.00248836,  0.02876855],
       [ 0.84844114, -1.18127848,  0.21164257, -0.3976746 ,  0.41037896],
       [-1.03981332,  0.2348126 , -1.03252476, -0.02076836, -0.32630507]])

In [72]:
np.divide(array1,array2)

array([[-2.09068384e+00,  1.16182797e-01, -8.44405474e-01,
        -2.10883799e+00,  2.01774997e-01],
       [-5.95258712e+00, -1.44967809e+00, -7.12951014e-01,
        -9.93472370e-01,  1.57514432e+00],
       [-5.54797898e-01,  2.00084423e-01,  3.88922928e-01,
         2.88560821e+00,  8.51207599e-02],
       [ 1.47746393e+00,  1.69925279e+00,  1.24556660e+00,
        -1.30066600e+00,  7.69726962e-01],
       [-8.96373164e-01,  4.29365580e+00, -1.31084017e+01,
        -1.06344908e-02,  3.59591634e+00]])

In [73]:
np.floor_divide(array1,array2)

array([[ -3.,   0.,  -1.,  -3.,   0.],
       [ -6.,  -2.,  -1.,  -1.,   1.],
       [ -1.,   0.,   0.,   2.,   0.],
       [  1.,   1.,   1.,  -2.,   0.],
       [ -1.,   4., -14.,  -1.,   3.]])

### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [74]:
array1 = np.random.randn(5, 5)
array1

array([[-1.82696555, -0.99078029,  0.11327346,  1.03442142, -0.1690099 ],
       [-0.27554146, -0.42618332,  0.525345  ,  1.12448855,  0.09821624],
       [ 0.82794386, -1.08445304, -1.1311904 ,  0.64584919, -0.36814842],
       [-0.95935229, -0.06745281,  0.16590813, -1.06299897,  0.3767082 ],
       [-1.33036183, -0.73624575,  0.6927515 ,  1.4931329 ,  0.3778742 ]])

In [75]:
array2 = np.random.randn(5, 5)
array2

array([[-0.48009753,  1.27936473, -0.50404174,  1.11407827,  1.5359149 ],
       [ 0.20213254,  0.2345026 , -1.22192661,  1.45186248, -0.0541716 ],
       [-1.35410385, -0.68062674,  0.24163727,  1.75602037,  0.68892716],
       [-0.09237148,  0.08345261,  0.90616139,  0.39578733, -2.4278325 ],
       [-0.50047975,  0.10551108, -0.337633  ,  0.68455239,  0.43936345]])

In [76]:
# Fusión condicional
np.where(array1 < array2, array1, array2)

array([[-1.82696555, -0.99078029, -0.50404174,  1.03442142, -0.1690099 ],
       [-0.27554146, -0.42618332, -1.22192661,  1.12448855, -0.0541716 ],
       [-1.35410385, -1.08445304, -1.1311904 ,  0.64584919, -0.36814842],
       [-0.95935229, -0.06745281,  0.16590813, -1.06299897, -2.4278325 ],
       [-1.33036183, -0.73624575, -0.337633  ,  0.68455239,  0.3778742 ]])

In [77]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[ 0.        ,  0.        , -0.50404174,  1.03442142,  0.        ],
       [ 0.        ,  0.        , -1.22192661,  1.12448855, -0.0541716 ],
       [-1.35410385,  0.        ,  0.        ,  0.64584919,  0.        ],
       [ 0.        ,  0.        ,  0.16590813,  0.        , -2.4278325 ],
       [ 0.        ,  0.        , -0.337633  ,  0.68455239,  0.3778742 ]])

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por filas</li>
<li>Valor 1: Aplicará la función por columnas</li>

In [78]:
array = np.random.randn(5, 4)
array

array([[ 0.83340822, -1.12239117, -1.58460471, -1.47680449],
       [ 0.5812192 ,  0.27123413, -0.66840905, -0.94156034],
       [-0.04126163,  0.1310486 , -0.23365507, -1.2276185 ],
       [-0.27246698,  1.44171313, -0.56219385, -0.19565487],
       [-0.23454859, -2.25884249, -1.79205984,  1.36706859]])

In [79]:
# Operación global
np.sum(array)

-7.986379716909038

In [80]:
# Operación por filas
np.sum(array, axis=0)

array([ 0.86635021, -1.5372378 , -4.84092251, -2.47456961])

In [81]:
# Operación por columnas
np.sum(array, axis=1)

array([-3.35039215, -0.75751606, -1.3714866 ,  0.41139743, -2.91838234])

Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [82]:
array.sum()

-7.986379716909038

In [83]:
np.argmax(array)

13

In [84]:
np.argmin(array)

17

In [85]:
np.cumsum(array)

array([ 0.83340822, -0.28898295, -1.87358766, -3.35039215, -2.76917295,
       -2.49793882, -3.16634787, -4.10790821, -4.14916984, -4.01812125,
       -4.25177632, -5.47939481, -5.75186179, -4.31014866, -4.87234251,
       -5.06799738, -5.30254597, -7.56138846, -9.3534483 , -7.98637972])

In [86]:
np.cumprod(array)

array([ 8.33408217e-01, -9.35410021e-01,  1.48225512e+00, -2.18900102e+00,
       -1.27228941e+00, -3.45088313e-01,  2.30660151e-01, -2.17180450e-01,
        8.96122037e-03,  1.17435535e-03, -2.74394082e-04,  3.36851250e-04,
       -9.17808417e-05, -1.32321645e-04,  7.43904147e-05, -1.45548472e-05,
        3.41381895e-06, -7.71127929e-06,  1.38190739e-05,  1.88916218e-05])

### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [87]:
array = np.random.randn(5, 5)
array

array([[ 1.460325  ,  1.05509947, -0.37654675,  0.17251588,  1.53569881],
       [ 0.95343245, -0.65136594, -0.56682218,  0.93058591,  0.50010254],
       [-0.08935621,  0.26001777,  0.71341341, -0.16297674, -0.77515651],
       [ 0.11060242, -1.33041189, -0.11492152,  0.95755154, -0.52131692],
       [-0.34443428, -0.83229595,  0.97127332, -0.98187992,  0.54774733]])

In [88]:
# Elementos mayores que 0
(array > 0).sum()

13

In [89]:
# Elementos menores que la media
(array < array.mean()).sum()

13

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [90]:
# Alguno de los elementos cumple la condición
(array == 0).any()

False

In [91]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

True

### Ordenación de ndarrays

In [92]:
array = np.random.randn(5, 5)
array

array([[-1.50940596,  2.75412441, -0.05287273, -0.26014579, -0.01331111],
       [ 1.54312454,  1.01279869, -0.27920878,  0.70515996,  0.28702026],
       [-1.06836272,  0.36590154, -1.1015435 ,  0.49599964, -1.75793654],
       [ 1.81211903,  1.11394135, -1.00003099,  0.20192286, -0.31619043],
       [-0.52140469,  0.52716394, -1.63106579, -0.32594348, -2.08938078]])

In [93]:
# Datos ordenados
np.sort(array) 

array([[-1.50940596, -0.26014579, -0.05287273, -0.01331111,  2.75412441],
       [-0.27920878,  0.28702026,  0.70515996,  1.01279869,  1.54312454],
       [-1.75793654, -1.1015435 , -1.06836272,  0.36590154,  0.49599964],
       [-1.00003099, -0.31619043,  0.20192286,  1.11394135,  1.81211903],
       [-2.08938078, -1.63106579, -0.52140469, -0.32594348,  0.52716394]])

In [94]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

array([[-1.50940596,  0.36590154, -1.63106579, -0.32594348, -2.08938078],
       [-1.06836272,  0.52716394, -1.1015435 , -0.26014579, -1.75793654],
       [-0.52140469,  1.01279869, -1.00003099,  0.20192286, -0.31619043],
       [ 1.54312454,  1.11394135, -0.27920878,  0.49599964, -0.01331111],
       [ 1.81211903,  2.75412441, -0.05287273,  0.70515996,  0.28702026]])

### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [95]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [96]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [97]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [98]:
np.union1d(array1, array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [99]:
np.in1d(array1, array2)

array([ True, False, False, False,  True,  True,  True,  True])

# Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. Todas estas funciones están disponibles a través del submódulo <b>linalg</b>.

In [100]:
import numpy as np
import numpy.linalg as linalg

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [101]:
array1 = np.random.randn(3, 3)
array1

array([[-0.99502127,  0.26816177, -0.0509226 ],
       [ 1.14670601,  1.49148389, -2.06604498],
       [-0.43427035,  0.96406213, -0.52480975]])

In [102]:
np.diag(array1)

array([-0.99502127,  1.49148389, -0.52480975])

In [103]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
np.dot(array, array)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [105]:
linalg.inv(array1)

array([[-1.35798394, -0.10292994,  0.53697547],
       [-1.68367771, -0.56168397,  2.37457786],
       [-1.96916648, -0.94662652,  2.01224933]])

In [106]:
linalg.solve(array1,array)

array([[ 2.91306302,  1.98912461,  1.06518621],
       [12.56241525, 12.69163143, 12.82084761],
       [ 9.23361641,  8.33007274,  7.42652908]])

In [107]:
q,r = linalg.qr(array)
print(q)
print('\n')
print(r)

[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]


[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.65307819e-16]]


# Generación de números aleatorios

Aunque el core de Pyhton incluye un modulo <b>random</b> para llevar a cabo la generación de números aleatorios, NumPy ofrece una mejora sobre el mismo permitiendo generar directamente ndarrays de valores aleatorios en base a diversas distribuciones. Todas estas funciones están disponibles a través del submódulo <b>random</b>.<br/>

In [108]:
import numpy as np
import numpy.random as random

Algunas de las más comunes son:
<ul>
<li><b>seed:</b> Establecimiento de semilla del generador de números aleatorios.</li>
<li><b>permutation:</b> Devuelve una permutación aleatoria de una secuencia de entrada (por copia).</li>
<li><b>shuffle:</b> Aplica una permutación aleatoria sobre los elementos de la secuencia de entrada (sin copia).</li>
<li><b>rand:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme.</li>
<li><b>randint:</b> Genera una muestra de números aleatorios enteros dentro de un rango definido.</li>
<li><b>randn:</b> Genera una muestra de números aleatorios utilizando una distribución normal de media 0 y desviación 1.</li>
<li><b>binomial:</b> Genera una muestra de números aleatorios utilizando una distribución binomial.</li>
<li><b>normal:</b> Genera una muestra de números aleatorios utilizando una distribución normal.</li>
<li><b>beta:</b> Genera una muestra de números aleatorios utilizando una distribución beta.</li>
<li><b>chisquare:</b> Genera una muestra de números aleatorios utilizando una distribución chi cuadrado.</li>
<li><b>gamma:</b> Genera una muestra de números aleatorios utilizando una distribución gamma.</li>
<li><b>uniform:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme [0, 1).</li>


</ul>

In [109]:
random.seed(42)

In [110]:
random.rand()

0.3745401188473625

In [111]:
random.randn(5)

array([-1.11188012,  0.31890218,  0.27904129,  1.01051528, -0.58087813])

In [112]:
random.binomial(1, 0.5, 10)

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [113]:
array_per = np.arange(9)
random.permutation(array_per)

array([1, 5, 4, 8, 0, 7, 6, 3, 2])

In [114]:
array_per

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
random.shuffle(array_per)

In [116]:
array_per

array([7, 2, 5, 8, 3, 1, 0, 4, 6])